name: 'Create Deployment Action'
description: 'Create Deployment event on GitHub. https://developer.github.com/v3/repos/deployments/#create-a-deployment'
author: 'yuichielectric'
inputs:
  ref:
    description: 'The ref to deploy'
  environment:
    description: 'Name for the target deployment environment (e.g., `production`, `staging`, `qa`)'
    default: 'production'
runs:
  using: 'node12'
  main: 'lib/main.js'
